### ISSUE TITLE
Incorrect computation on version v0.1.1

### ISSUE THREAD

**Issue by bertram-gil** [scallop-lang/scallop-lang.github.io#6]
Hi guys, 
Thanks so much for fixing https://github.com/scallop-lang/scallop-lang.github.io/issues/3. 
I came across another similar bug. 
Consider the following Scallop program: 

```
rel a__ = { 
	("ir", 38, 59),
	("iz", 68, 32),
	("as", 59, 69),
	("ir", 49, 77),
}
rel b__ = {       // Output node
	(69, "cj"),
	(81, "it"),
	(97, "at"),
	(25, "bm"),
	(22, "ye"),
}


rel b__(b, a) = a__(a, b, b)

query b__
```

When I run this program with the latest Scallop executable (`v0.1.1` for Linux), I get:

```
$ ./scli program.scl
b__: {(22, "ye"), (25, "bm"), (69, "cj"), (81, "it"), (97, "at")}
```

If I now add a subgoal `a__(a, b, b)` in the only rule for relation `b__` to get the following new program: 

```
rel a__ = { 
	("ir", 38, 59),
	("iz", 68, 32),
	("as", 59, 69),
	("ir", 49, 77),
}
rel b__ = {       // Output node
	(69, "cj"),
	(81, "it"),
	(97, "at"),
	(25, "bm"),
	(22, "ye"),
}


rel b__(b, a) = a__(a, b, b), a__(a, b, b)

query b__

```

I get: 
```
$ ./scli program.scl
b__: {(22, "ye"), (25, "bm"), (38, "ir"), (49, "ir"), (59, "as"), (68, "iz"), (69, "cj"), (81, "it"), (97, "at")}
```
Adding this subgoal should not add extra tuples in the result. 
Please let me know if you cannot reproduce the bug. 

The bug is present in both `v0.1.0` and `v0.1.1`.

**Comment by Liby99** [comment]
Thanks! Fixed in `v0.1.2`.
